name: cc206_sign_wave
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Black.ttf
        - asset: fonts/Lato/Lato-BlackItalic.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
        - asset: fonts/Lato/Lato-BoldItalic.ttf
        - asset: fonts/Lato/Lato-Italic.ttf
        - asset: fonts/Lato/Lato-Light.ttf
        - asset: fonts/Lato/Lato-LightItalic.ttf
        - asset: fonts/Lato/Lato-Thin.ttf
        - asset: fonts/Lato/Lato-ThinItalic.ttf
        


